Repository lausalbra/nailing, pull requests merged in 2022-03, with the labels that each got.

#46 Task-032: #39 completada y modificaciones a la configuración del proyecto
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  pom.xml
  src/main/java/com/nailing/APP/Centro/Centro.java
  src/main/java/com/nailing/APP/Centro/CentroRepository.java
  src/main/resources/application.properties
Labels: enhancement

#64 feat: implementación reserva y cambios de configuración del proyecto
  pom.xml
  src/main/java/com/nailing/app/reserva/Reserva.java
  src/main/java/com/nailing/app/reserva/ReservaController.java
  src/main/java/com/nailing/app/reserva/ReservaRepository.java
  src/main/java/com/nailing/app/reserva/ReservaService.java
Labels: enhancement

#67 fix: Relacion acabado y base con uña
  src/main/java/com/nailing/app/unya/Unya.java
Labels: bug

#71 feat: Implementar Security en la app y el login de usuarios
  pom.xml
  src/main/java/com/nailing/app/base/BaseController.java
  src/main/java/com/nailing/app/securityConfiguration/DbInit.java
  src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java
  src/main/java/com/nailing/app/securityConfiguration/UserPrincipal.java
  src/main/java/com/nailing/app/securityConfiguration/UserPrincipalDetailsService.java
  src/main/java/com/nailing/app/usuario/Usuario.java
  src/main/java/com/nailing/app/usuario/UsuarioRepository.java
Labels: enhancement

#74 feat : Crear controlador CRUD de Centro
  src/main/java/com/nailing/app/centro/CentroController.java
  src/main/java/com/nailing/app/centro/CentroService.java
Labels: enhancement

#75 feat: Creacion de Tamanyo, sus operaciones y endpoints
  src/main/java/com/nailing/app/base/BaseController.java
  src/main/java/com/nailing/app/tamanyo/NombreTamanyo.java
  src/main/java/com/nailing/app/tamanyo/Tamanyo.java
  src/main/java/com/nailing/app/tamanyo/TamanyoController.java
  src/main/java/com/nailing/app/tamanyo/TamanyoRepository.java
  src/main/java/com/nailing/app/tamanyo/TamanyoService.java
Labels: enhancement

#84 feat: Añadido controlador y cambios de diseño de la app
  src/main/java/com/nailing/app/base/BaseService.java
  src/main/java/com/nailing/app/tipo/NombreTipo.java
  src/main/java/com/nailing/app/tipo/Tipo.java
  src/main/java/com/nailing/app/tipo/TipoController.java
  src/main/java/com/nailing/app/tipo/TipoRepository.java
  src/main/java/com/nailing/app/tipo/TipoService.java
Labels: enhancement

#81 Task 042: Modelo, Repositorio, creación, eliminado y listado de Acabado
  src/main/java/com/nailing/app/acabado/Acabado.java
  src/main/java/com/nailing/app/acabado/AcabadoController.java
  src/main/java/com/nailing/app/acabado/AcabadoRepository.java
  src/main/java/com/nailing/app/acabado/AcabadoService.java
  src/main/java/com/nailing/app/acabado/NombreAcabado.java
  src/main/java/com/nailing/app/centro/Centro.java
Labels: enhancement

#82 Task 026: Modelo, Repositorio, Creación, Eliminación, Listado de decoración
  src/main/java/com/nailing/app/centro/Centro.java
  src/main/java/com/nailing/app/decoracion/Decoracion.java
  src/main/java/com/nailing/app/decoracion/DecoracionController.java
  src/main/java/com/nailing/app/decoracion/DecoracionRepository.java
  src/main/java/com/nailing/app/decoracion/DecoracionService.java
  src/main/java/com/nailing/app/decoracion/NombreDecoracion.java
Labels: enhancement

#76 Task 066 implementar GitHub action Backend #66
  .github/workflows/ci.yml
  src/test/java/com/nailing/APP/AppApplicationTests.java
Labels: enhancement

#80 feat: Modelo, Repositorio, creación, eliminación y listado de Forma
  src/main/java/com/nailing/app/forma/Forma.java
  src/main/java/com/nailing/app/forma/FormaController.java
  src/main/java/com/nailing/app/forma/FormaRepository.java
  src/main/java/com/nailing/app/forma/FormaService.java
  src/main/java/com/nailing/app/forma/NombreForma.java
Labels: enhancement

#85 Task 025 modelo repositorio creacion eliminación y listado de diseño #25
  src/main/java/com/nailing/app/disenyo/Disenyo.java
  src/main/java/com/nailing/app/disenyo/DisenyoController.java
  src/main/java/com/nailing/app/disenyo/DisenyoRepository.java
  src/main/java/com/nailing/app/disenyo/DisenyoService.java
  src/main/java/com/nailing/app/disenyo/NombreDisenyo.java
Labels: enhancement

#88 feat: Terminada la creacion del endpoint
  src/main/java/com/nailing/app/decoracion/DecoracionService.java
  src/main/java/com/nailing/app/forma/FormaRepository.java
  src/main/java/com/nailing/app/tamanyo/TamanyoService.java
Labels: enhancement

#90 fix: Adecuado Filtrado Decoraciones
  src/main/java/com/nailing/app/decoracion/DecoracionService.java
  src/main/java/com/nailing/app/disenyo/Disenyo.java
Labels: enhancement

#95 Task 041 modelo y repositorio de uña #41
  src/main/java/com/nailing/app/acabado/Acabado.java
  src/main/java/com/nailing/app/centro/Centro.java
  src/main/java/com/nailing/app/cita/Cita.java
  src/main/java/com/nailing/app/cita/CitaController.java
  src/main/java/com/nailing/app/cita/CitaRepository.java
  src/main/java/com/nailing/app/cita/CitaService.java
  src/main/java/com/nailing/app/decoracion/Decoracion.java
  src/main/java/com/nailing/app/unya/Dedo.java
  src/main/java/com/nailing/app/unya/Unya.java
Labels: enhancement

#96 fix: errores en los atributos de centro
  src/main/java/com/nailing/app/centro/Centro.java
  src/main/java/com/nailing/app/cita/Cita.java
  src/main/java/com/nailing/app/cita/CitaController.java
  src/main/java/com/nailing/app/cita/CitaService.java
Labels: enhancement

#99 Task 041 modelo y repositorio de uña #41
  src/main/java/com/nailing/app/decoracion/DecoracionController.java
  src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java
Labels: enhancement

#105 feat: Añadidas imágenes a los centros
  src/main/resources/application.properties
  src/main/resources/data.sql
Labels: bug

#106 Task 042 modelo repositorio creacion eliminacion y listado de acabado
  src/main/java/com/nailing/app/acabado/AcabadoController.java
Labels: bug

#104 fix: solucionado error con orígenes cruzados
  src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java
Labels: bug

#108 feat: endpoint login hecho
  src/main/java/com/nailing/app/securityConfiguration/DbInit.java
  src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java
  src/main/java/com/nailing/app/securityConfiguration/UserPrincipal.java
  src/main/java/com/nailing/app/usuario/Usuario.java
  src/main/java/com/nailing/app/usuario/UsuarioController.java
  src/main/java/com/nailing/app/usuario/UsuarioRepository.java
  src/main/java/com/nailing/app/usuario/UsuarioService.java
Labels: enhancement

#117 fix: errores de cors y en security
  src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java
  src/main/resources/application.properties
Labels: bug, BackEnd

#125 fix: error cors
  pom.xml
  src/main/java/com/nailing/app/AppApplication.java
Labels: bug, BackEnd

#126 fix: cors configuration
  src/main/java/com/nailing/app/AppApplication.java
  src/main/java/com/nailing/app/acabado/AcabadoController.java
  src/main/java/com/nailing/app/base/BaseController.java
  src/main/java/com/nailing/app/centro/CentroController.java
  src/main/java/com/nailing/app/cita/CitaController.java
  src/main/java/com/nailing/app/decoracion/DecoracionController.java
  src/main/java/com/nailing/app/disenyo/DisenyoController.java
  src/main/java/com/nailing/app/forma/FormaController.java
  src/main/java/com/nailing/app/reserva/ReservaController.java
  src/main/java/com/nailing/app/tamanyo/TamanyoController.java
  src/main/java/com/nailing/app/tipo/TipoController.java
  src/main/java/com/nailing/app/usuario/UsuarioController.java
Labels: bug, BackEnd

#133 fix: Cambio en la configuración de CORS
  src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java
Labels: bug, BackEnd

#141 fix: Error en endpoint
  src/main/java/com/nailing/app/cita/CitaController.java
Labels: enhancement, BackEnd

#143 fix: detalles de centros público
  src/main/java/com/nailing/app/centro/CentroController.java
  src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java
Labels: bug, BackEnd

#153 fix: Arreglado un problema con el nombre de siguiente fase en Tamaños
  src/main/java/com/nailing/app/tamanyo/Tamanyo.java
Labels: bug, BackEnd

#154 junit añadido al pom
  pom.xml
Labels: bug, BackEnd

#173 fix: Se pueden borrar las diferentes uñas si existen citas
  src/main/resources/data.sql
Labels: bug, BackEnd

#174 Develop frontend
  src/web-app/src/components/LoginForm/index.js
  src/web-app/src/components/UserDetails/index.js
Labels: FrontEnd

#177 Feature/#031 personalización de uña
  src/web-app/src/components/PropertyPanel/index.js
  src/web-app/src/static/ACRILICO.PNG
  src/web-app/src/static/ACRYGEL.PNG
  src/web-app/src/static/ALMOND.PNG
  src/web-app/src/static/BABY_BOOMER.PNG
  src/web-app/src/static/BALLERINA.PNG
  src/web-app/src/static/BRILLO.PNG
  src/web-app/src/static/BURBUJAS.PNG
  src/web-app/src/static/DEGRADADO_COLOR.PNG
  src/web-app/src/static/DIBUJO.PNG
  src/web-app/src/static/DISNEY_BOCETO.PNG
  src/web-app/src/static/DISNEY_COLOR.PNG
  src/web-app/src/static/DUAL_SYSTEM.PNG
  src/web-app/src/static/EFECTO_HUEVO.PNG
  src/web-app/src/static/EFECTO_RELIEVE.PNG
  src/web-app/src/static/ENCAPSULADO.PNG
  src/web-app/src/static/ESCULPIDA.PNG
  src/web-app/src/static/ESPEJO.PNG
  src/web-app/src/static/FRANCESA.PNG
  src/web-app/src/static/FRANCESA_REVERSA.PNG
  src/web-app/src/static/GEL.PNG
  src/web-app/src/static/HOLOGRAFICO.PNG
  src/web-app/src/static/LISAS.PNG
  src/web-app/src/static/MARMOL.PNG
  src/web-app/src/static/MATE.PNG
  src/web-app/src/static/NATURAL.PNG
  src/web-app/src/static/PAN_DE_ANGEL.PNG
  src/web-app/src/static/PEGATINAS.PNG
  src/web-app/src/static/PIEDRAS.PNG
  src/web-app/src/static/PIERCING.PNG
  src/web-app/src/static/ROUND.PNG
  src/web-app/src/static/SEMIPERMANENTE.PNG
  src/web-app/src/static/SEMIPERMANENTE_REFUERZO.PNG
  src/web-app/src/static/SQUARE.PNG
  src/web-app/src/static/SQUOVAL.PNG
  src/web-app/src/static/STANPING.PNG
  src/web-app/src/static/STILETTO.PNG
  src/web-app/src/static/SUGAR.PNG
  src/web-app/src/static/TRANSFER_FOIL.PNG
  src/web-app/tailwind.config.js
Labels: FrontEnd

#175 refactor: Limpieza del código de listado de centros y citas
  src/web-app/src/components/CenterList/index.js
  src/web-app/src/components/CitasList/index.js
  src/web-app/src/components/Filter/index.js
  src/web-app/src/components/Header/index.js
  src/web-app/src/components/RestUtils/index.js
Labels: FrontEnd

#178 fix: Corregido fallos al listar y borrar citas
  src/web-app/src/App.js
  src/web-app/src/components/CenterList/index.js
  src/web-app/src/components/CitasList/index.js
Labels: FrontEnd

#172 feat: Implementado Logout
  src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java
Labels: BackEnd

#207 Feature/task 045 login usuario
  src/web-app/src/components/Header/index.js
  src/web-app/src/components/LoginForm/index.js
  src/web-app/src/components/RestUtils/index.js
  src/web-app/src/components/UserDetails/index.js
Labels: FrontEnd

#210 Feature/#066 implementar GitHub action
  .github/workflows/ci.yml
Labels: enhancement, BackEnd

#213 Feature/#167 calendario centros
  src/main/java/com/nailing/app/centro/Centro.java
  src/main/java/com/nailing/app/cita/Cita.java
  src/main/java/com/nailing/app/cita/CitaController.java
  src/main/java/com/nailing/app/cita/CitaRepository.java
  src/main/java/com/nailing/app/cita/CitaService.java
  src/main/resources/data.sql
Labels: enhancement, BackEnd

#218 fix: ids de usuarios reseteadas
  src/main/java/com/nailing/app/usuario/Usuario.java
  src/main/resources/data.sql
Labels: bug, BackEnd

#219 feat: Registro de Usuarios
  src/main/java/com/nailing/app/usuario/Usuario.java
  src/main/java/com/nailing/app/usuario/UsuarioController.java
  src/main/java/com/nailing/app/usuario/UsuarioService.java
Labels: enhancement, BackEnd

#223 fix: Error 401 solucionado
  src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java
Labels: enhancement, BackEnd

#224 Mergeo de develop a local previo a finalización de tarea
  src/web-app/package-lock.json
  src/web-app/package.json
  src/web-app/public/index.html
  src/web-app/src/components/FeedbackForm/index.js
  src/web-app/src/components/Paypal/PayPal.js
  src/web-app/src/components/PropertyPanel/index.js
Labels: FrontEnd

#225 Feature/#164 calendario cita
  src/web-app/src/components/CenterDetails/index.js
  src/web-app/src/components/PropertyPanel/index.js
Labels: FrontEnd
