Repository lausalbra/nailing, pull requests merged in 2022-05, with the labels that each got.

#448 Tests de frontend
  src/web-app/package-lock.json
  src/web-app/package.json
  src/web-app/src/App.test.js
  src/web-app/src/tests/BookingsList.test.js
  src/web-app/src/tests/Centro.test.js
  src/web-app/src/tests/CentroAdd.test.js
  src/web-app/src/tests/CentroEdit.test.js
  src/web-app/src/tests/Cita.test.js
  src/web-app/src/tests/ComprarPaquete.test.js
  src/web-app/src/tests/Conocenos.test.js
  src/web-app/src/tests/DemoServiciosCentro.test.js
  src/web-app/src/tests/EditarUsuario.test.js
  src/web-app/src/tests/Error.test.js
  src/web-app/src/tests/Feedback.test.js
  src/web-app/src/tests/Landing.test.js
  src/web-app/src/tests/Login.test.js
  src/web-app/src/tests/Logout.test.js
  src/web-app/src/tests/MisCitasList.test.js
  src/web-app/src/tests/RegistroUsuario.test.js
  src/web-app/src/tests/ServiciosCentro.test.js
  src/web-app/src/tests/TerminosCondiciones.test.js
  src/web-app/src/tests/Usuario.test.js
Labels: FrontEnd

#447 Feature/#446 validacion centros
  src/web-app/src/components/CenterDetails/index.js
  src/web-app/src/components/PropertyPanel/index.js
  src/web-app/src/components/ServiciosList/index.js
  src/web-app/src/components/UserDetails/index.js
Labels: FrontEnd

#451 feat: endpoint creado
  src/main/java/com/nailing/app/cita/CitaController.java
  src/main/java/com/nailing/app/cita/CitaService.java
Labels: enhancement, BackEnd

#459 fix: validación usuario-centro
  src/main/java/com/nailing/app/cita/CitaController.java
  src/main/java/com/nailing/app/cita/CitaService.java
Labels: enhancement, BackEnd

#461 Feature/#449 reservas centro
  src/web-app/src/App.js
  src/web-app/src/components/CitaCentro/index.js
  src/web-app/src/components/CitaCentroList/index.js
  src/web-app/src/components/UserDetails/index.js
  src/web-app/src/views/CentroCitas/index.js
Labels: FrontEnd

#463 Errores menores
  src/web-app/src/components/EditarUsuarioForm/index.js
  src/web-app/src/components/Header/index.js
  src/web-app/src/components/RegistroCentroForm/index.js
  src/web-app/src/components/RegistroUsuarioForm/index.js
Labels: FrontEnd

#467 Feature/#429 testing back
  pom.xml
  src/main/java/com/nailing/app/base/Base.java
  src/main/java/com/nailing/app/valoracion/ValoracionService.java
  src/test/java/com/nailing/APP/acabado/AcabadoControllerTest.java
  src/test/java/com/nailing/APP/acabado/AcabadoServiceTest.java
  src/test/java/com/nailing/APP/base/BaseServiceTest.java
  src/test/java/com/nailing/APP/centro/CentroServiceTest.java
  src/test/java/com/nailing/APP/cita/CitaServiceTest.java
  src/test/java/com/nailing/APP/tamanyo/TamayoServiceTest.java
  src/test/java/com/nailing/APP/valoracion/ValoracionServiceTest.java
Labels: enhancement, BackEnd, test

#470 Develop frontend
  src/web-app/src/components/CenterDetails/index.js
  src/web-app/src/components/UserDetails/index.js
Labels: FrontEnd

#476 Required añadidos
  src/web-app/src/components/CentroEditForm/index.js
Labels: FrontEnd

#477 Required telefono
  src/web-app/src/components/EditarUsuarioForm/index.js
Labels: FrontEnd

#478 feat: ordenado por valoración y cita pasada
  src/main/java/com/nailing/app/centro/CentroRepository.java
  src/main/java/com/nailing/app/securityConfiguration/DbInit.java
  src/main/resources/data.sql
Labels: enhancement, BackEnd

#521 Feature/minor fixes sprint5
  src/web-app/src/components/Center/index.js
  src/web-app/src/components/CentroEditForm/index.js
  src/web-app/src/components/RegistroCentroForm/index.js
  src/web-app/src/components/RegistroServiciosCentroForm/index.js
Labels: FrontEnd

#522 Develop frontend
  src/web-app/src/components/Center/index.js
  src/web-app/src/components/CentroEditForm/index.js
  src/web-app/src/components/RegistroCentroForm/index.js
  src/web-app/src/components/RegistroServiciosCentroForm/index.js
Labels: FrontEnd

#523 fix creditos
  src/main/java/com/nailing/app/centro/CentroService.java
Labels: bug, BackEnd

#515 fix: Anotación Positive
  src/main/java/com/nailing/app/acabado/Acabado.java
  src/main/java/com/nailing/app/decoracion/Decoracion.java
Labels: enhancement, BackEnd

#527 Feature/minor fixes sprint5
  src/web-app/src/App.js
  src/web-app/src/components/Header/index.js
Labels: FrontEnd

#528 Develop frontend
  src/web-app/src/App.js
  src/web-app/src/components/Header/index.js
Labels: FrontEnd

#530 Eliminada validación de calle
  src/web-app/src/components/CentroEditForm/index.js
  src/web-app/src/components/RegistroCentroForm/index.js
Labels: FrontEnd

#531 Develop frontend
  src/web-app/src/components/CentroEditForm/index.js
  src/web-app/src/components/RegistroCentroForm/index.js
Labels: FrontEnd
