Repository lausalbra/nailing, pull requests merged in 2022-04, with the labels that each got.

#226 feat: Ordenado por Premium
  src/main/java/com/nailing/app/centro/Centro.java
  src/main/java/com/nailing/app/centro/CentroService.java
  src/main/java/com/nailing/app/centro/Suscripcion.java
  src/main/resources/data.sql
Labels: enhancement, BackEnd

#234 fix: Suscripción NotNull
  src/main/java/com/nailing/app/centro/Centro.java
Labels: enhancement, BackEnd

#235 fix: Security Configurado
  src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java
Labels: enhancement, BackEnd

#238 feat: Añadir personalizaciones a centros #205
  src/main/java/com/nailing/app/acabado/Acabado.java
  src/main/java/com/nailing/app/acabado/AcabadoController.java
  src/main/java/com/nailing/app/acabado/AcabadoService.java
  src/main/java/com/nailing/app/base/Base.java
  src/main/java/com/nailing/app/base/BaseController.java
  src/main/java/com/nailing/app/base/BaseService.java
  src/main/java/com/nailing/app/decoracion/Decoracion.java
  src/main/java/com/nailing/app/decoracion/DecoracionController.java
  src/main/java/com/nailing/app/decoracion/DecoracionService.java
  src/main/java/com/nailing/app/disenyo/Disenyo.java
  src/main/java/com/nailing/app/disenyo/DisenyoController.java
  src/main/java/com/nailing/app/disenyo/DisenyoService.java
  src/main/java/com/nailing/app/forma/Forma.java
  src/main/java/com/nailing/app/forma/FormaController.java
  src/main/java/com/nailing/app/forma/FormaService.java
  src/main/java/com/nailing/app/securityConfiguration/DbInit.java
  src/main/java/com/nailing/app/tamanyo/Tamanyo.java
  src/main/java/com/nailing/app/tamanyo/TamanyoController.java
  src/main/java/com/nailing/app/tamanyo/TamanyoService.java
  src/main/java/com/nailing/app/tipo/Tipo.java
  src/main/java/com/nailing/app/tipo/TipoController.java
  src/main/java/com/nailing/app/tipo/TipoService.java
Labels: enhancement, BackEnd

#240 Feature/#166 edit usuario
  src/main/java/com/nailing/app/usuario/UsuarioController.java
Labels: enhancement

#243 feat: Listado por centro
  src/main/java/com/nailing/app/acabado/AcabadoController.java
  src/main/java/com/nailing/app/acabado/AcabadoService.java
  src/main/java/com/nailing/app/base/BaseController.java
  src/main/java/com/nailing/app/base/BaseService.java
  src/main/java/com/nailing/app/decoracion/DecoracionController.java
  src/main/java/com/nailing/app/decoracion/DecoracionService.java
  src/main/java/com/nailing/app/disenyo/DisenyoController.java
  src/main/java/com/nailing/app/disenyo/DisenyoService.java
  src/main/java/com/nailing/app/forma/FormaController.java
  src/main/java/com/nailing/app/forma/FormaService.java
  src/main/java/com/nailing/app/tamanyo/TamanyoController.java
  src/main/java/com/nailing/app/tamanyo/TamanyoService.java
  src/main/java/com/nailing/app/tipo/TipoController.java
  src/main/java/com/nailing/app/tipo/TipoService.java
Labels: enhancement, BackEnd

#245 fix: Arreglado error 400
  src/main/java/com/nailing/app/securityConfiguration/DbInit.java
  src/main/java/com/nailing/app/usuario/UsuarioController.java
  src/main/java/com/nailing/app/usuario/UsuarioService.java
Labels: enhancement, BackEnd

#247 fix: error edit usuario
  src/main/java/com/nailing/app/centro/CentroService.java
  src/main/java/com/nailing/app/securityConfiguration/DbInit.java
  src/main/java/com/nailing/app/usuario/Usuario.java
  src/main/java/com/nailing/app/usuario/UsuarioController.java
  src/main/java/com/nailing/app/usuario/UsuarioService.java
Labels: bug, BackEnd

#249 fix: error bucle autowired
  src/main/java/com/nailing/app/securityConfiguration/DbInit.java
Labels: bug, BackEnd

#253 Feature/#159 listado negocios admin
  src/web-app/package-lock.json
  src/web-app/package.json
  src/web-app/src/components/Center/index.js
  src/web-app/src/components/CenterList/index.js
  src/web-app/src/components/Cita/index.js
  src/web-app/src/components/CitasList/index.js
  src/web-app/src/components/Filter/index.js
Labels: FrontEnd

#254 feat: Documentacion Api
  pom.xml
Labels: enhancement, BackEnd

#256 fix: error añandir centro no se vincula
  src/main/java/com/nailing/app/centro/CentroService.java
  src/main/java/com/nailing/app/usuario/UsuarioService.java
Labels: bug, BackEnd

#259 Feature/ task 201 modificación de centros #201
  src/web-app/src/App.js
  src/web-app/src/components/CentroEditForm/index.js
  src/web-app/src/components/RegistroCentroForm/index.js
  src/web-app/src/views/CentroAdd/index.js
  src/web-app/src/views/CentroEdit/index.js
Labels: FrontEnd

#260 fix: Se puede hacer carga inicial sin tener que borrar las citas antes
  src/main/resources/data.sql
Labels: bug, BackEnd

#255 feat: Documentación Swagger
  src/main/java/com/nailing/app/acabado/AcabadoController.java
  src/main/java/com/nailing/app/base/BaseController.java
  src/main/java/com/nailing/app/centro/CentroController.java
  src/main/java/com/nailing/app/cita/CitaController.java
  src/main/java/com/nailing/app/decoracion/DecoracionController.java
  src/main/java/com/nailing/app/disenyo/DisenyoController.java
  src/main/java/com/nailing/app/forma/FormaController.java
  src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java
  src/main/java/com/nailing/app/tamanyo/TamanyoController.java
  src/main/java/com/nailing/app/tipo/TipoController.java
  src/main/java/com/nailing/app/usuario/UsuarioController.java
  src/main/resources/application.properties
Labels: enhancement, BackEnd

#265 fix: errores varios
  src/main/java/com/nailing/app/acabado/Acabado.java
  src/main/java/com/nailing/app/acabado/AcabadoService.java
  src/main/java/com/nailing/app/base/BaseService.java
Labels: bug, BackEnd

#267 Feature/#158 registro servicios centro
  src/web-app/src/App.js
  src/web-app/src/components/LoginForm/index.js
  src/web-app/src/components/RegistroServiciosCentroForm/index.js
  src/web-app/src/components/RestUtils/index.js
  src/web-app/src/components/Servicio/index.js
  src/web-app/src/components/ServiciosBox/index.js
  src/web-app/src/components/ServiciosList/index.js
  src/web-app/src/components/UserDetails/index.js
  src/web-app/src/services/common/common.js
  src/web-app/src/views/DemoServiciosCentro/index.js
  src/web-app/src/views/ServiciosCentro/index.js
Labels: FrontEnd

#271 fix: Cambiadas imagenes de centros
  src/main/resources/data.sql
Labels: bug, BackEnd

#272 refactor: Mejora de Codigo
  src/main/java/com/nailing/app/acabado/AcabadoController.java
  src/main/java/com/nailing/app/acabado/AcabadoService.java
  src/main/java/com/nailing/app/base/BaseController.java
  src/main/java/com/nailing/app/base/BaseService.java
  src/main/java/com/nailing/app/centro/Centro.java
  src/main/java/com/nailing/app/centro/CentroController.java
  src/main/java/com/nailing/app/centro/CentroRepository.java
  src/main/java/com/nailing/app/centro/CentroService.java
  src/main/java/com/nailing/app/cita/CitaController.java
  src/main/java/com/nailing/app/cita/CitaService.java
  src/main/java/com/nailing/app/decoracion/DecoracionController.java
  src/main/java/com/nailing/app/decoracion/DecoracionService.java
  src/main/java/com/nailing/app/disenyo/DisenyoController.java
  src/main/java/com/nailing/app/disenyo/DisenyoService.java
  src/main/java/com/nailing/app/forma/FormaController.java
  src/main/java/com/nailing/app/forma/FormaService.java
  src/main/java/com/nailing/app/securityConfiguration/SecurityConfiguration.java
  src/main/java/com/nailing/app/securityConfiguration/UserPrincipal.java
  src/main/java/com/nailing/app/securityConfiguration/UserPrincipalDetailsService.java
  src/main/java/com/nailing/app/tamanyo/TamanyoController.java
  src/main/java/com/nailing/app/tamanyo/TamanyoService.java
  src/main/java/com/nailing/app/tipo/TipoController.java
  src/main/java/com/nailing/app/tipo/TipoService.java
  src/main/java/com/nailing/app/usuario/Usuario.java
  src/main/java/com/nailing/app/usuario/UsuarioController.java
  src/main/java/com/nailing/app/usuario/UsuarioRepository.java
  src/main/java/com/nailing/app/usuario/UsuarioService.java
  src/test/java/com/nailing/APP/AppApplicationTests.java
Labels: enhancement, BackEnd

#273 fix: Edit fix
  src/main/java/com/nailing/app/centro/CentroController.java
  src/main/java/com/nailing/app/usuario/UsuarioController.java
Labels: bug, BackEnd

#276 fix: Edit centro
  src/main/java/com/nailing/app/centro/CentroController.java
Labels: bug, BackEnd

#279 Develop frontend
  src/web-app/package-lock.json
  src/web-app/package.json
  src/web-app/src/components/CenterDetails/index.js
  src/web-app/src/components/CentroEditForm/index.js
  src/web-app/src/components/Filter/provincias.js
  src/web-app/src/components/RegistroCentroForm/index.js
  src/web-app/src/components/RegistroServiciosCentroForm/index.js
  src/web-app/src/components/UserDetails/index.js
  src/web-app/src/views/CentroAdd/index.js
Labels: FrontEnd

#282 Develop frontend
  src/web-app/src/components/RegistroServiciosCentroForm/index.js
  src/web-app/src/components/UserDetails/index.js
Labels: FrontEnd

#333 feat: Añadido listado vacío de citas y arreglados bad smells
  src/web-app/src/components/CenterList/index.js
  src/web-app/src/components/CitasList/index.js
  src/web-app/src/components/ServiciosList/index.js
Labels: FrontEnd

#334 feat/Adición de clases tailwind y modelo
  src/web-app/src/App.js
  src/web-app/src/index.css
  src/web-app/src/views/Landing/index.js
  src/web-app/tailwind.config.js
Labels: FrontEnd

#335 feat/Unificación de fondos y fuentes
  src/web-app/src/components/CenterDetails/index.js
  src/web-app/src/components/PropertyPanel/index.js
  src/web-app/src/components/SlidingPane/react-sliding-pane.css
Labels: FrontEnd

#336 feat/Nuevas fotos para tamaño
  src/web-app/src/static/JAPONESA.PNG
  src/web-app/src/static/L.PNG
  src/web-app/src/static/M.PNG
  src/web-app/src/static/RELLENO.PNG
  src/web-app/src/static/S.PNG
  src/web-app/src/static/XL.PNG
  src/web-app/src/static/XS.PNG
  src/web-app/src/static/XXL.PNG
  src/web-app/src/static/XXS.PNG
  src/web-app/tailwind.config.js
Labels: FrontEnd

#339 feat/Reserva de cita responsive
  src/web-app/src/components/PropertyPanel/PropertyPanel.css
  src/web-app/src/components/PropertyPanel/index.js
  src/web-app/src/components/SlidingPane/react-sliding-pane.css
  src/web-app/tailwind.config.js
Labels: FrontEnd

#352 Develop frontend
  src/web-app/src/components/UserDetails/index.js
Labels: FrontEnd

#354 feat: creado el endpoint para cambiar la imagen
  src/main/java/com/nailing/app/centro/CentroController.java
  src/main/java/com/nailing/app/centro/CentroService.java
  src/main/resources/data.sql
Labels: enhancement, BackEnd

#355 feat: Añadidos los días disponibles para el centro en la entidad. Aho…
  src/main/java/com/nailing/app/centro/Centro.java
  src/main/java/com/nailing/app/centro/CentroService.java
  src/main/java/com/nailing/app/cita/CitaService.java
  src/main/resources/data.sql
Labels: enhancement, BackEnd

#358 Feature/#353 terminos condiciones
  src/web-app/src/App.js
  src/web-app/src/components/RegistroUsuarioForm/index.js
  src/web-app/src/views/Conocenos/index.js
  src/web-app/src/views/TerminosCondiciones/index.js
Labels: FrontEnd

#359 feat: Añadido plan de suscripciones al formulario de centro
  src/web-app/src/components/RegistroCentroForm/index.js
Labels: FrontEnd

#361 Develop frontend
  src/web-app/src/App.js
  src/web-app/src/components/RegistroCentroForm/index.js
  src/web-app/src/components/RegistroUsuarioForm/index.js
  src/web-app/src/views/Conocenos/index.js
  src/web-app/src/views/TerminosCondiciones/index.js
Labels: FrontEnd

#365 Feature/#328 suscripción centros
  src/web-app/src/components/Center/index.js
  src/web-app/src/components/Cita/index.js
  src/web-app/src/components/Filter/index.js
  src/web-app/src/components/RegistroCentroForm/index.js
  src/web-app/src/components/Servicio/index.js
  src/web-app/src/components/ServiciosBox/index.js
Labels: FrontEnd

#369 Feature/#305 implementar valoraciones
  src/main/java/com/nailing/app/centro/Centro.java
  src/main/java/com/nailing/app/centro/CentroService.java
  src/main/java/com/nailing/app/usuario/UsuarioService.java
  src/main/java/com/nailing/app/valoracion/Valoracion.java
  src/main/java/com/nailing/app/valoracion/ValoracionController.java
  src/main/java/com/nailing/app/valoracion/ValoracionRepository.java
  src/main/java/com/nailing/app/valoracion/ValoracionService.java
  src/main/resources/data.sql
Labels: enhancement, BackEnd

#374 fix/horas de apertura y cierre
  src/main/java/com/nailing/app/centro/CentroService.java
Labels: bug, BackEnd

#373 fix/valoracion datasql
  src/main/resources/data.sql
Labels: bug, BackEnd

#385 Develop frontend
  src/web-app/package-lock.json
  src/web-app/package.json
  src/web-app/src/components/BurgerHeader/index.js
  src/web-app/src/components/CardWorker/index.js
  src/web-app/src/components/Center/index.js
  src/web-app/src/components/CenterDetails/index.js
  src/web-app/src/components/CenterList/index.js
  src/web-app/src/components/CentroEditForm/index.js
  src/web-app/src/components/Cita/index.js
  src/web-app/src/components/CitasList/index.js
  src/web-app/src/components/EditarUsuarioForm/index.js
  src/web-app/src/components/Filter/index.js
  src/web-app/src/components/Header/index.js
  src/web-app/src/components/LoginForm/index.js
  src/web-app/src/components/Paypal/PayPal.js
  src/web-app/src/components/PropertyPanel/index.js
  src/web-app/src/components/RegistroCentroForm/index.js
  src/web-app/src/components/RegistroServiciosCentroForm/index.js
  src/web-app/src/components/RestUtils/index.js
  src/web-app/src/components/Servicio/index.js
  src/web-app/src/components/ServiciosBox/index.js
  src/web-app/src/components/ServiciosList/index.js
  src/web-app/src/components/UserDetails/index.js
  src/web-app/src/static/Logo-Completo.png
  src/web-app/src/views/Centro/index.js
  src/web-app/src/views/Cita/index.js
  src/web-app/src/views/Conocenos/index.js
  src/web-app/src/views/Landing/index.js
  src/web-app/src/views/Usuario/index.js
Labels: FrontEnd

#387 Feature/#343 revision formulario centro
  src/web-app/src/components/CentroEditForm/index.js
  src/web-app/src/components/Paypal/PayPal.js
  src/web-app/src/components/RegistroCentroForm/index.js
  src/web-app/src/components/UserDetails/index.js
Labels: FrontEnd

#390 fix: Cambio estructura de carpetas
  src/test/java/com/nailing/APP/forma/FormaTestService.java
  src/test/java/com/nailing/APP/tamanyo/TamayoTestService.java
Labels: enhancement, BackEnd

#392 fix centro con 0 creditos y creditos negativos
  src/main/java/com/nailing/app/securityConfiguration/DbInit.java
  src/main/resources/data.sql
Labels: bug, BackEnd

#384 Test/#307 jacobo
  pom.xml
  src/main/java/com/nailing/app/decoracion/Decoracion.java
  src/main/resources/data.sql
  src/test/java/com/nailing/APP/decoracion/DecoServiceTest.java
  src/test/java/com/nailing/APP/disenyo/DisenyoServiceTest.java
Labels: BackEnd, test

#394 Test/#307 hegoa
  src/main/java/com/nailing/app/tamanyo/TamanyoController.java
  src/main/java/com/nailing/app/tipo/TipoController.java
  src/main/java/com/nailing/app/usuario/Usuario.java
  src/test/java/com/nailing/APP/tipo/TipoServiceTest.java
  src/test/java/com/nailing/APP/usuario/UsuarioServiceTest.java
Labels: BackEnd, test

#395 fix/test centro
  src/test/java/com/nailing/APP/centro/CentroTestService.java
Labels: BackEnd, test

#386 Test/#307 canjorbus
  src/test/java/com/nailing/APP/acabado/AcabadoTestService.java
  src/test/java/com/nailing/APP/base/BaseTestService.java
Labels: BackEnd, test

#401 fix test findall centro
  src/test/java/com/nailing/APP/centro/CentroTestService.java
Labels: bug, BackEnd, test

#405 refactor: SonarLint
  pom.xml
  src/main/java/com/nailing/app/centro/CentroService.java
  src/main/java/com/nailing/app/cita/CitaService.java
  src/main/java/com/nailing/app/decoracion/Decoracion.java
  src/main/java/com/nailing/app/securityConfiguration/DbInit.java
  src/main/java/com/nailing/app/usuario/UsuarioService.java
  src/main/java/com/nailing/app/valoracion/ValoracionController.java
  src/main/java/com/nailing/app/valoracion/ValoracionService.java
  src/test/java/com/nailing/APP/acabado/AcabadoServiceTest.java
  src/test/java/com/nailing/APP/base/BaseServiceTest.java
  src/test/java/com/nailing/APP/centro/CentroServiceTest.java
  src/test/java/com/nailing/APP/cita/CitaServiceTest.java
  src/test/java/com/nailing/APP/forma/FormaServiceTest.java
  src/test/java/com/nailing/APP/tamanyo/TamayoServiceTest.java
  src/test/java/com/nailing/APP/tipo/TipoServiceTest.java
  src/test/java/com/nailing/APP/usuario/UsuarioServiceTest.java
Labels: enhancement, BackEnd

#409 Fix creacion de base
  src/main/java/com/nailing/app/base/BaseService.java
Labels: bug, BackEnd

#411 Fix/minor fixes sprint3 front
  src/web-app/src/App.js
  src/web-app/src/components/Card/index.js
  src/web-app/src/components/Center/index.js
  src/web-app/src/components/CenterDetails/index.js
  src/web-app/src/components/CenterList/index.js
  src/web-app/src/components/CentroEditForm/index.js
  src/web-app/src/components/ComprarPaqueteComponent/index.js
  src/web-app/src/components/CreditosAtrasadosComponent/index.js
  src/web-app/src/components/EditarUsuarioForm/index.js
  src/web-app/src/components/FeedbackForm/index.js
  src/web-app/src/components/LoginForm/index.js
  src/web-app/src/components/Paypal/PayPal.js
  src/web-app/src/components/PropertyPanel/index.js
  src/web-app/src/components/RegistroCentroForm/index.js
  src/web-app/src/components/RegistroServiciosCentroForm/index.js
  src/web-app/src/components/RegistroUsuarioForm/index.js
  src/web-app/src/components/ServiciosList/index.js
  src/web-app/src/components/SuscripcionComponent/index.js
  src/web-app/src/components/UserDetails/index.js
  src/web-app/src/static/NO_DECORACION.PNG
  src/web-app/src/views/Centro/index.js
  src/web-app/src/views/Conocenos/index.js
  src/web-app/src/views/LogOut/index.js
  src/web-app/tailwind.config.js
Labels: FrontEnd

#412 Develop frontend
  src/web-app/package-lock.json
  src/web-app/package.json
  src/web-app/src/App.js
  src/web-app/src/components/BurgerHeader/index.js
  src/web-app/src/components/Card/index.js
  src/web-app/src/components/CardWorker/index.js
  src/web-app/src/components/Center/index.js
  src/web-app/src/components/CenterDetails/index.js
  src/web-app/src/components/CenterList/index.js
  src/web-app/src/components/CentroEditForm/index.js
  src/web-app/src/components/Cita/index.js
  src/web-app/src/components/CitasList/index.js
  src/web-app/src/components/ComprarPaqueteComponent/index.js
  src/web-app/src/components/CreditosAtrasadosComponent/index.js
  src/web-app/src/components/EditarUsuarioForm/index.js
  src/web-app/src/components/FeedbackForm/index.js
  src/web-app/src/components/Filter/index.js
  src/web-app/src/components/Header/index.js
  src/web-app/src/components/LoginForm/index.js
  src/web-app/src/components/Paypal/PayPal.js
  src/web-app/src/components/PropertyPanel/index.js
  src/web-app/src/components/RegistroCentroForm/index.js
  src/web-app/src/components/RegistroServiciosCentroForm/index.js
  src/web-app/src/components/RegistroUsuarioForm/index.js
  src/web-app/src/components/RestUtils/index.js
  src/web-app/src/components/Servicio/index.js
  src/web-app/src/components/ServiciosBox/index.js
  src/web-app/src/components/ServiciosList/index.js
  src/web-app/src/components/SuscripcionComponent/index.js
  src/web-app/src/components/UserDetails/index.js
  src/web-app/src/static/Logo-Completo.png
  src/web-app/src/static/NO_DECORACION.PNG
  src/web-app/src/views/Centro/index.js
  src/web-app/src/views/Cita/index.js
  src/web-app/src/views/ComprarPaquete/index.js
  src/web-app/src/views/Conocenos/index.js
  src/web-app/src/views/CreditosAtrasados/index.js
  src/web-app/src/views/Landing/index.js
  src/web-app/src/views/LogOut/index.js
  src/web-app/src/views/Usuario/index.js
  src/web-app/tailwind.config.js
Labels: FrontEnd

#414 Fix/minor fixes sprint3 front
  src/web-app/src/components/Center/index.js
  src/web-app/src/components/CenterDetails/index.js
  src/web-app/src/components/Cita/index.js
  src/web-app/src/components/CitasList/index.js
  src/web-app/src/components/RegistroServiciosCentroForm/index.js
  src/web-app/src/components/ServiciosList/index.js
  src/web-app/src/components/UserDetails/index.js
Labels: FrontEnd

#415 Fix/#305 update valoracion
  src/main/java/com/nailing/app/valoracion/ValoracionController.java
  src/main/java/com/nailing/app/valoracion/ValoracionService.java
Labels: bug, BackEnd

#417 fix: imagenes centros de prueba
  src/main/resources/data.sql
Labels: bug, BackEnd

#420 Develop frontend
  src/web-app/src/components/CenterDetails/index.js
Labels: FrontEnd
